
package br.com.fiap.winery.stubclasses;

import jakarta.jws.WebMethod;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "WineWarningService", targetNamespace = "http://winery.fiap.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WineWarningService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendWarn", targetNamespace = "http://winery.fiap.com.br/", className = "br.com.fiap.winery.stubclasses.SendWarn")
    @ResponseWrapper(localName = "sendWarnResponse", targetNamespace = "http://winery.fiap.com.br/", className = "br.com.fiap.winery.stubclasses.SendWarnResponse")
    @Action(input = "http://winery.fiap.com.br/WineWarningService/sendWarnRequest", output = "http://winery.fiap.com.br/WineWarningService/sendWarnResponse")
    public String sendWarn();

}
